### ISSUE TITLE
v2.4.0

### ISSUE THREAD

**Issue by Conjuro** [streamlink/streamlink-chocolatey#66] opened 2021-09-07 11:33 UTC
v2.4.0 released: https://github.com/streamlink/streamlink/releases/tag/2.4.0

**Comment by Conjuro** [comment] 2021-09-07 11:41
I'll do this one tomorrow. Gonna have to set up a VM for testing the package before pushing it live. I'm on W7.

**Comment by nateify** [comment] 2021-12-09 18:24
Is this package still maintained? A new major version 3.0 has since been released for Streamlink

**Comment by brian6932** [comment] 2021-12-09 19:24
@nateify read through #67
> Chocolatey verification servers are running on Windows Server 2012 R2, which is causing the verification testing to fail.

**Comment by scowalt** [comment] 2021-12-09 20:26
Thanks again for all of the work @Conjuro

**Comment by IeUDE** [comment] 2022-02-11 06:18
Is this still maintained, we are multiple versions behind ...

LATEST is 3.1.1
https://github.com/streamlink/streamlink/releases

@Conjuro

**Comment by scowalt** [comment] 2022-02-16 19:06
> Is this still maintained, we are multiple versions behind ...
> 
> LATEST is 3.1.1 https://github.com/streamlink/streamlink/releases
> 
> @Conjuro

Thanks for the ping, I know it's frustrating to have the chocolatey version so out-of-date.

Right now I'm not maintaining this package. Anyone is free to contribute a pull request though! IIRC we had some issues getting newer versions working in chocolatey's continuous integration system.

**Comment by gep13** [comment] 2022-02-16 22:20
@scowalt :wave: Chocolatey Team member here...

If there is something that we can help with, feel free to reach out and ask.

**Comment by scowalt** [comment] 2022-02-16 22:35
> @scowalt 👋 Chocolatey Team member here...
> 
> If there is something that we can help with, feel free to reach out and ask.

Hey, thanks for dropping in!

From the PR: https://github.com/streamlink/streamlink-chocolatey/pull/67#issuecomment-917171189

It looks like we were having issues getting a build working with Windows Server 2012 R2. Does chocolatey still use that version in its validation system?

**Comment by scowalt** [comment] 2022-02-16 22:35
It's also possible that we're not blocked on anything besides dev time, I don't have deep context on that issue.

**Comment by gep13** [comment] 2022-02-17 07:33
> @scowalt said...
Does chocolatey still use that version in its validation system?

Yes, the package-verifier, which is part of the package moderation services uses Windows Server 2012 R2 as the primary operating system for testing of installation of packages.

Is streamlink intended to work on that Operating System?  If not, you can request an exemption from the package-verifier.

If the issue is something like a dependency of the streamlink package needing a reboot before things will install correctly, then this is also a reason to request an exemption.

You can use the following:

https://github.com/chocolatey-community/chocolatey-test-environment

As a test bed for testing out the installation of the streamlink package.

**Comment by scowalt** [comment] 2022-02-19 16:10
Hopefully issue this will be fixed here: https://github.com/streamlink/streamlink/pull/4356

@gep13 , we'll probably need a package-verifier exemption for the next version. Windows Server 2012 R2 is based on Window 6.3, and `streamlink` is only designed to run on Windows 10

**Comment by gep13** [comment] 2022-02-19 20:07
>@scowalt said...
we'll probably need a package-verifier exemption for the next version. Windows Server 2012 R2 is based on Window 6.3, and streamlink is only designed to run on Windows 10

Once the package is pushed, if you reply in the moderation comment textbox on the package version page on community.chocolatey.org, one of the moderators can provide that exemption.

**Comment by lorthris** [comment] 2022-02-24 11:56
So reading this thread and https://github.com/streamlink/streamlink/pull/4356 - should we expect updates to streamlink on chocolately soon? with twitch killing the old API only GUI2.0 works that requires Streamlink 2.4 min but only 2.3 is available. Ive had to manually uninstall and update using the .exe

**Comment by scowalt** [comment] 2022-02-28 03:50
I just merged in some code that should automate version updates!

The first example is live now - https://community.chocolatey.org/packages/streamlink/3.1.1

**Comment by scowalt** [comment] 2022-02-28 15:00
@gep13 , can you help give us an exemption? Or should I just wait? https://community.chocolatey.org/packages/streamlink/3.1.1

**Comment by gep13** [comment] 2022-03-04 07:25
@scowalt an exemption for this package has now been provided.  It will still need to pass through the other package moderation checks, but once that is complete, the package should then be available for installation.

**Comment by scowalt** [comment] 2022-03-04 14:30
Thanks! I think the package was approved.

I'm leaving this issue open for now. I saw some reports that `streamlink-twitch-gui@2.0.0` isn't compatible with `streamlink@3.1.1`. So, we may end up needing to ship the latest `streamlink@2.x.x` and update the dependency range in `streamlink-twitch-gui`

**Comment by bastimeyer** [comment] 2022-03-04 15:23
> I saw some reports that `streamlink-twitch-gui@2.0.0` isn't compatible with `streamlink@3.1.1`

Wrong. People simply don't read and are confused about breaking changes of Streamlink's 3.0.0 release on Windows.
https://github.com/streamlink/streamlink-twitch-gui/issues/842#issuecomment-973369948

If there are any incompatibilities, these will be handled accordingly. And Streamlink Twitch GUI `2.0.0` requires Streamlink `>=2.4.0`, as described in its changelog.

**Comment by scowalt** [comment] 2022-03-04 15:46
Good to know! I'll point folks to that issue if there are concerns.

I still need to bump the minimum version of `streamlink` for `streamlink-twitch-gui` to `2.4.0`, but other than that we should be good!

**Closed as completed** 2022-03-04 15:48 UTC
Labels: version-update
